### ISSUE TITLE
Feature: User can post games they own to be borrowed.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can post games they own to be borrowed.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- The user can fill out a form with the info about their game.
- The user can search for a specific game in the api.
- When searching for a game, a different view with the results of their search will show.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-1-user-can-post-games](https://user-images.githubusercontent.com/78943990/119545116-4c939480-bd47-11eb-842b-912dab575920.PNG)
![feature-1-user-can-post-games-mobile](https://user-images.githubusercontent.com/78943990/119545126-51584880-bd47-11eb-85e4-ac94acbc4fb1.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a table with the following information about the game post:
- - [x] Lender's name
- - [x] Game title
- - [x] Game's image file path
- - [x] Lender's comments 
- [x] Update `data.sql` to insert a few data entries

### ☁️ Server

- [x] Update `server/index.js` to handle post requests to add new game posts to the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create HTML skeleton with root div in server.
- [x] Add script tags, css links and links for font awesome
- [x] Create a component to update dom with correct view
- [x] Create a component with a `form` for "New Post's"
- [x] Create a component that changes to a "game search" view.
- [x] Add a click handler to the "Name of Game" input that changes to this view.
- [x] Create a list component that updates the dom with the top 10 results of the inputted name in the search bar.
- [x] Prepare and send a request to the public api with the results from the search.
- [x] Grab the information from the api about the title of the game, and the thumbnail of the game and create the list item accordingly 
- [x] When the user selects an item from the result's list, the new post form is updated with the name and image of that game.
- [x] Add a submit handler to the form.  
- [x] When submitted:
- - [x] Reset the form entries
- - [x] Reset the search input and the list of results
- - [x] Send a POST request to the server with the information previously mentioned about the game post. 
- [x] touch up styling in CSS.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
