### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#17]
## 🐛 Bug
Some conversation titles aren't displaying the name of the person you are having a conversation with.

#### Desired Behavior

> ##### The app should ...

The app should display the name of the person that you are having the conversation with when you are viewing the chat of a created conversation.

#### Actual Behavior

> ##### The app does this instead ...

On the first opened conversation, it displays a different name than the person that is a part of the conversation. However the list of conversations shows the correct name.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [ ] ... Track the code and the values of requests from the database to the backend, to the front end, and on the page.
- [ ] ...
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
