### ISSUE TITLE
Feature: User can search for posted games.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for posted games.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User can see a list of current posted games with the name of the game and lender
- The user can search for the name of a game specifically.
- When the user selects a posting, they will set details of the game and lender

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-2-user-can-search-posts](https://user-images.githubusercontent.com/78943990/119552673-a1d3a400-bd4f-11eb-8dbe-24cbfc4fc3a8.PNG)
![feature-2-user-can-search-posts-mobile](https://user-images.githubusercontent.com/78943990/119552715-af892980-bd4f-11eb-8fa7-7ec43c40609f.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include:
- - [x] number of players (min, max)
- - [x] Play time (min, max)
- - [x] Age range
- - [x] published year
- - [x] description
- - [x] an image Url
- [x] Update `data.sql` to include the columns above.

### ☁️ Server

- [x] Update app.post `/api/boardGameInfo/` in `server/index.js` to also accept/require the columns added in database.
- [x] Change db query to include the updated sql
- [x] Create another GET route that pulls up to 10 posts in the database sorting by most recently created.
- [x] Create another GET route, that queries the database for all matching names or games based on the user's search and return up to 10.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update App component to change views based on `<a>` pressed.
- [x] Update `<Header />` to include an icon for searching for posts and adding posts
- [x] Create `<Posts />` component to switch between postings list, search modal, and a PostInfo view.
- [x] Create a PostInfo component.
- [x] Update the PostInfo component with the info of the selected game from either the search view and the posting list view.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
