### ISSUE TITLE
Feature: User can send a message to a lender.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can send a message to a lender.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- The user can send a message to a lender through their game post
- A modal will appear, and they can cancel by clicking blank space, or the cancel button.
- After the message is sent, a confirmation is shown for a half a second, before returning to the view of the game post.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-3-user-can-message-a-lender](https://user-images.githubusercontent.com/78943990/119552998-0262e100-bd50-11eb-966f-08fcd730646e.PNG)
![feature-3-user-can-message-a-lender-mobile](https://user-images.githubusercontent.com/78943990/119553003-042ca480-bd50-11eb-82d8-ec4f65da3b6f.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a third table for messages with senderId, recipientId, timeOfMessage, content, and relative postId.
- [x] recipientId should be equal to userId, 
- [x] Update `data.sql` to add a few messages to the messages database

### ☁️ Server

- [x] Update `server/index.js` to handle post requests for sent messages and add them to the messages database. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a "Message Lender" button to the PostInfo page.
- [x] Create a modal for the `<Post />` component that shows when that button is pressed.
- [x] Grab the postId from the route path and send that to the message component.
- [x] In the modal, make a form with a textarea, and two buttons, one being cancel, and one being send.
- [x] Hide the modal when the cancel button is pressed.
- [x] Show a "message sent" prompt when the send button is clicked. and hide the modal after 2 seconds, returning to the PostInfo page.
- [x] when the send button is pressed, send a request to the server to update the message into the database.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
