### ISSUE TITLE
Feature: User can view a list of conversations.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of conversations.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- User can click on the messages' icon, and change to a view of a list of their messages between lenders.
- The list items will have info of the lender's name, the date of the last message, and the beginning of the last message sent from the conversation.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-4-user-can-view-a-list-of-conversations](https://user-images.githubusercontent.com/78943990/119553606-a3ea3280-bd50-11eb-8ef4-962f49877a12.PNG)
![feature-4-user-can-view-a-list-of-conversations-mobile](https://user-images.githubusercontent.com/78943990/119553622-a77db980-bd50-11eb-9586-2f6769e0df02.PNG)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET requests for /api/messages/:userId that returns all of the messages with matching recipientId or senderId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to send a request to the server to grab all messages for the user.
- [x] Filter through the user and combine the matching recipientId/senderId into an array to make a conversation.
- [x] organize them by the most recent message.
- [x] Show the date of the most recent message in the conversation, the lender's name associated with it, and the beginning of the most recent message.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
