### ISSUE TITLE
Feature: User can respond to a conversation.

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can respond to a conversation.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- When selecting a conversation from the list of conversations in the previous feature, a standard styled message window will show with the history of each message sent in that conversation.
- The user can send a new message by typing into the input down at the bottom of the message window.
- After the user sends their message, they will see the conversation update with their' conversation.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-5-user-can-respond-to-a-conversation](https://user-images.githubusercontent.com/78943990/119554541-a7ca8480-bd51-11eb-82bc-fc6e0e456b5b.PNG)
![feature-5-user-can-respond-to-a-conversation-mobile](https://user-images.githubusercontent.com/78943990/119554547-a8fbb180-bd51-11eb-95fd-81d7064675fc.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
