### ISSUE TITLE
Feature: User can sign-up

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Going to make a sign-up feature where a user can make a new account that includes there username, password. The account will be used to keep track of messages, game posts they have made and more.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-6-user-can-sign-up](https://user-images.githubusercontent.com/78943990/120871374-4f189a00-c550-11eb-809c-ba5c3cd2e71a.PNG)
![feature-6-user-can-sign-up-mobile](https://user-images.githubusercontent.com/78943990/120871394-5a6bc580-c550-11eb-902e-a94c880ba265.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create a new table "users" with a userId, username, and password

### ☁️ Server

- [x] Update `server/index.js` to accept post requests that updates the "users" table with a new user and their info
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render a form allowing users to "sign-up"
- [x] Create a hash-routing system, and remove any "view-swapping" systems in place.
- [x] Update header component to have a "create account" link that sends the user to the "sign-up" form. 

### 🧑‍⚕️ Clean Up

- [x] Check hash-routing system and make sure 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
