### ISSUE TITLE
Feature: User can sign-in

### ISSUE THREAD

**Issue by alexdenbaugh** [alexdenbaugh/phoenix-games#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create sign-in route handler on backend, going to add sign-in handling to App component via methods.  Going to make a redirect component that will redirect the user to the sign-in page if they aren't signed in.  Going to change the AuthoForm to be dynamic and change to sign-in or sign-up depending on the situation.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![feature-6-user-can-sign-in](https://user-images.githubusercontent.com/78943990/120871442-7c654800-c550-11eb-9089-bf1530b38937.PNG)
![feature-7-user-can-sign-in-mobile](https://user-images.githubusercontent.com/78943990/120871446-7ec7a200-c550-11eb-9a4b-ed6f4b664236.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle Post requests to api/auth/sign-in
- [x] Check credentials, query database, and create token to send back to client.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to redirect users to sign-in page if they aren't signed-in
- [x] Update AuthForm component to handle sign-in or sign-up situations.
- [x] Change "sign-up" button to be "sign-in/sign-up
- [x] Add sign-out button and sign-out handler 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
